# Generated by Django 4.2.11 on 2024-04-24 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('T', 'Técnico'), ('S', 'Soft Skills'), ('P', 'PBL')], max_length=1, null=True, verbose_name='Tipo do Mentor')),
                ('email_ifpb', models.CharField(max_length=100, null=True)),
                ('email_polo', models.CharField(max_length=100, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentores_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentores_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentores',
            },
        ),
    ]
