# Generated by Django 4.2.11 on 2024-04-24 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('email_academico', models.CharField(max_length=100, null=True)),
                ('email_polo', models.CharField(max_length=100, null=True)),
                ('matricula', models.CharField(max_length=24, null=True, verbose_name='Matrícula')),
                ('curso', models.CharField(max_length=100, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discentes_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discentes_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discentes_mentorados', to='capacitacao.mentor')),
            ],
            options={
                'verbose_name': 'Discente',
                'verbose_name_plural': 'Discentes',
            },
        ),
    ]
