# Generated by Django 4.2.11 on 2024-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacao', '0002_discente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='email_academico',
            field=models.EmailField(max_length=100, null=True, verbose_name='E-mail Acadêmico'),
        ),
        migrations.AlterField(
            model_name='discente',
            name='email_polo',
            field=models.EmailField(max_length=100, null=True, verbose_name='E-mail Polo de Inovação'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email_ifpb',
            field=models.EmailField(max_length=100, null=True, verbose_name='E-mail Ifpb'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email_polo',
            field=models.EmailField(max_length=100, null=True, verbose_name='E-mail Polo de Inovação'),
        ),
    ]
