# Generated by Django 4.2.11 on 2024-04-24 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacitacao', '0003_alter_discente_email_academico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('R', 'Real'), ('E', 'Espelho')], max_length=1, null=True, verbose_name='Tipo do Projeto')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('autalizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projetos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projetos_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
