# Generated by Django 4.2.11 on 2024-04-25 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacitacao', '0004_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscenteProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('B', 'Bolsista'), ('V', 'Voluntário')], max_length=1, null=True, verbose_name='Vínculo')),
                ('data_entrada', models.DateField(null=True, verbose_name='Data de Entrada')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discente_projetos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discente_projetos_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('discente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discente_projetos', to='capacitacao.discente')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discente_projetos', to='capacitacao.projeto')),
            ],
            options={
                'verbose_name': 'Discente Projeto',
                'verbose_name_plural': 'Discente Projetos',
            },
        ),
    ]
