# Generated by Django 4.2.11 on 2024-04-25 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacitacao', '0005_discenteprojeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoavaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.DecimalField(decimal_places=0, default=1, max_digits=2, null=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autoavaliações_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autoavaliações_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('discente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autoavaliações', to='capacitacao.discente')),
            ],
            options={
                'verbose_name': 'Autoavaliação',
                'verbose_name_plural': 'Autoavaliações',
            },
        ),
    ]
