# Generated by Django 4.2.11 on 2024-04-26 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacitacao', '0008_subsoftskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoavaliacaoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('autoavaliacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='capacitacao.autoavaliacao')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('soft_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='capacitacao.softskill')),
                ('sub_soft_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='capacitacao.subsoftskill')),
            ],
            options={
                'verbose_name': 'Nota da Autoavaliação',
                'verbose_name_plural': 'Notas das Autoavaliações',
            },
        ),
    ]
