# Generated by Django 4.2.11 on 2024-05-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacao', '0009_autoavaliacaonota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discente',
            name='mentor',
        ),
        migrations.AddField(
            model_name='projeto',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='capacitacao.mentor'),
        ),
    ]
