# Generated by Django 4.2.11 on 2024-05-03 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacitacao', '0010_remove_discente_mentor_projeto_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoavaliacao',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autoavaliacoes_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autoavaliacao',
            name='cadastrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autoavaliacoes_cadastradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autoavaliacao',
            name='discente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autoavaliacoes', to='capacitacao.discente'),
        ),
    ]
