# Generated by Django 4.2.11 on 2025-03-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacao', '0011_alter_autoavaliacao_atualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsoftskill',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
