# Generated by Django 4.2.11 on 2025-07-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacao', '0012_alter_subsoftskill_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='nome_completo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
