# Generated by Django 4.2.11 on 2025-07-23 21:26

from django.db import migrations, models
import random


def gerar_cpf():
    cpf = [random.randint(0, 9) for _ in range(9)]
    soma1 = sum([(10 - i) * cpf[i] for i in range(9)])
    d1 = (soma1 * 10 % 11) % 10
    cpf.append(d1)
    soma2 = sum([(11 - i) * cpf[i] for i in range(10)])
    d2 = (soma2 * 10 % 11) % 10
    cpf.append(d2)

    return ''.join(map(str, cpf))


def generate_cpfs(apps, schema_editor):
    Discente = apps.get_model('capacitacao', 'Discente')
    updated_discentes = []
    for discente in Discente.objects.all():
        discente.cpf = gerar_cpf()
        updated_discentes.append(discente)

    Discente.objects.bulk_update(updated_discentes, fields=['cpf'])


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacao', '0013_mentor_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='discente',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.RunPython(generate_cpfs),
    ]
